version: 2
updates:
  - package-ecosystem: npm
    directory: /vocapet-desktop-friend
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns: ["*"]
  - package-ecosystem: maven
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      all-actions:
        patterns: ["*"]
