/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppPetsRouteImport } from './routes/app.pets'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppReaderRouteImport } from './routes/app.reader'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppWelcomeRouteImport } from './routes/app.welcome'
import { Route as AppDecksIndexRouteImport } from './routes/app.decks.index'
import { Route as AppDecksDeckIdRouteImport } from './routes/app.decks.$deckId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppPetsRoute = AppPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReaderRoute = AppReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppDecksIndexRoute = AppDecksIndexRouteImport.update({
  id: '/decks/',
  path: '/decks/',
  getParentRoute: () => AppRoute,
} as any)
const AppDecksDeckIdRoute = AppDecksDeckIdRouteImport.update({
  id: '/decks/$deckId',
  path: '/decks/$deckId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/pets': typeof AppPetsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reader': typeof AppReaderRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/welcome': typeof AppWelcomeRoute
  '/app/': typeof AppIndexRoute
  '/app/decks/$deckId': typeof AppDecksDeckIdRoute
  '/app/decks/': typeof AppDecksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/pets': typeof AppPetsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reader': typeof AppReaderRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/welcome': typeof AppWelcomeRoute
  '/app': typeof AppIndexRoute
  '/app/decks/$deckId': typeof AppDecksDeckIdRoute
  '/app/decks': typeof AppDecksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/pets': typeof AppPetsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reader': typeof AppReaderRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/welcome': typeof AppWelcomeRoute
  '/app/': typeof AppIndexRoute
  '/app/decks/$deckId': typeof AppDecksDeckIdRoute
  '/app/decks/': typeof AppDecksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/welcome'
    | '/app/achievements'
    | '/app/pets'
    | '/app/profile'
    | '/app/reader'
    | '/app/tasks'
    | '/app/welcome'
    | '/app/'
    | '/app/decks/$deckId'
    | '/app/decks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/welcome'
    | '/app/achievements'
    | '/app/pets'
    | '/app/profile'
    | '/app/reader'
    | '/app/tasks'
    | '/app/welcome'
    | '/app'
    | '/app/decks/$deckId'
    | '/app/decks'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/welcome'
    | '/app/achievements'
    | '/app/pets'
    | '/app/profile'
    | '/app/reader'
    | '/app/tasks'
    | '/app/welcome'
    | '/app/'
    | '/app/decks/$deckId'
    | '/app/decks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pets': {
      id: '/app/pets'
      path: '/pets'
      fullPath: '/app/pets'
      preLoaderRoute: typeof AppPetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reader': {
      id: '/app/reader'
      path: '/reader'
      fullPath: '/app/reader'
      preLoaderRoute: typeof AppReaderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/welcome': {
      id: '/app/welcome'
      path: '/welcome'
      fullPath: '/app/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/decks/': {
      id: '/app/decks/'
      path: '/decks'
      fullPath: '/app/decks/'
      preLoaderRoute: typeof AppDecksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/decks/$deckId': {
      id: '/app/decks/$deckId'
      path: '/decks/$deckId'
      fullPath: '/app/decks/$deckId'
      preLoaderRoute: typeof AppDecksDeckIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppPetsRoute: typeof AppPetsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReaderRoute: typeof AppReaderRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDecksDeckIdRoute: typeof AppDecksDeckIdRoute
  AppDecksIndexRoute: typeof AppDecksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppPetsRoute: AppPetsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReaderRoute: AppReaderRoute,
  AppTasksRoute: AppTasksRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppDecksDeckIdRoute: AppDecksDeckIdRoute,
  AppDecksIndexRoute: AppDecksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
