spring:
    datasource:
        url: jdbc:mysql://localhost:3306/vocab_pet
        username: root
        password: 0346443950

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

server:
    port: 8080
